### ISSUE TITLE
Child view management

### ISSUE THREAD

**Issue by ildarsharafutdinov** [k-o-d-e-n/CGLayout#1]
hi,

Does the tool support automatic subview management? 

Something like http://texturegroup.org/docs/automatic-subnode-mgmt.html

**Comment by k-o-d-e-n** [comment]
Hi,

Core of framework manages only layout process, therefore you must manage hierarchy yourself.
However, constraints have active state that depends on availability super. Therefore you can construct dynamic interface as like as in Autolayout, managing active state in constraints.
Also, framework provides class LayoutGuide (and his subclasses), that similar ASDisplayNode, and has interface for managing sub`s.

Thanks for question.

**Comment by ildarsharafutdinov** [comment]
Ok.

So how about the first feature request? :)

Automatic subview management allows me to create react like function to produce layout from view-model and I don't have to bother whether to add or remove views in view-hierarchy.

This is **very** useful in AsyncDisplayKit/Texture.

**Comment by k-o-d-e-n** [comment]
I understand you, but like you can see, I interrupted support this framework, because I spend for other project. And I don`t know when continue developing.
I would determine this feature like "convenience" improvement, and mark for future.
I saw example ASM and 'automatically' only in name of feature, because subnode`s manage handle in `layoutSpecThatFits:` method.
In my case, you can just define function, that will be update layout constraints, remove/add views , and call this function before invoking layout (aka updateConstraints in UIKit).

You can contribute if it very important for you.
If I have something misunderstood, please give me sample code.

**Comment by ildarsharafutdinov** [comment]
I didn't notice you stopped to support this framework. Sorry.

**Comment by k-o-d-e-n** [comment]
I didn't make changes for about one month.
I'll continue to support, but after some time. Unfortunately, I have no time at this moment, and I cannot maintain actively.
I thought that only I used this framework for internal targets
